.dockerfilelintrc:
  rules:
    latest_tag: "off"
    sudo_usage: "off"

.github/workflows/ci.yaml:
  env:
    - DOCKER_IMAGE: adorsys/ci-helm
      TAG: 2.16
      DIR: images/2.16
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/ci-helm
      TAG: 2.17
      DIR: images/2.17
      ALIASES: '2'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/ci-helm
      TAG: 3.3
      DIR: images/3.3
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/ci-helm
      TAG: 3.4
      DIR: images/3.4
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/ci-helm
      TAG: 3.5
      DIR: images/3.5
      ALIASES: '3 latest'
      SQUASH: 'true'
